### ISSUE TITLE
Function mcrypt_decrypt() is deprecated in PHP 7.1

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#218]
Обновил OpenServer и решил включить использование PHP 7.1. Получил на 0.96 (в 97 проверил код - всё также и ошибка тоже будет) серию ошибок:

> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_get_iv_size() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 291

> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_decrypt() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 300

> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_get_iv_size() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 273

> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_create_iv() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 274

> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_encrypt() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 275

**Comment by maxsite** [comment]
Нужно разбираться. Пока вот решение для CodeIgniter 3: https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/1053

**Comment by vimruler** [comment]
Да, нужно изучить вопрос. Так то да, по ссылке есть решение на основе функции random_bytes. Но первое что приходит в голову - а как будет проходить работа с паролями? Ведь если сперва их создали с одной функцией и сохранили в базе хеш, а потом решили проверить с другой, то может получится "Ой".

**Comment by maxsite** [comment]
Похоже, что нет возможности нормально запустить MaxSite CMS на php 7.1. Функции шифрования объявлены как deprecated, а в php 7.2 будут вовсе уделены. Так что единственный путь — это пока отказаться от использования новых версий PHP.

Решение, которое я вижу — это переход на CodeIgniter 3.x (или даже будущую 4-ку), где уже можно выбрать другую библиотеку шифрования. Но, как это скажется на существующих паролях, пока не ясно. Скорее всего придется их сбрасывать и заново создавать для каждого пользователя. :-(

**Comment by Fafofu** [comment]
Ндяя... вот тут предлагают какое-то решение...

This error occurs because you probably have something other than AES-256-CBC as your cipher in your config/app.php file that depends on the mcrypt extension. Perhaps you are using MCRYPT_RIJNDAEL_256 or MCRYPT_RIJNDAEL_128?

The best thing you can do without a full-blown Laravel upgrade is install the legacy encrypter and use it to update all your encrypted data to use the AES-256-CBC cipher which has been the default cipher since Laravel 5.1, I believe. Once you do this, you should be able to use PHP 7.1 for your Laravel application.

https://stackoverflow.com/questions/41031076/php7-1-and-laravel-5-3-function-mcrypt-get-iv-size-is-deprecated

**Comment by maxsite** [comment]
Не очень похоже на решение...

**Comment by zlolik** [comment]
DO NOT use this or any other encryption library for user password storage! Passwords must be hashed instead, and you should do that via PHP’s own Password Hashing extension.
https://www.codeigniter.com/user_guide/libraries/encryption.html

**Comment by maxsite** [comment]
Ну да, а то мы не в курсе...
